package com.checkmatey.core.engine

import com.checkmatey.core.chess.Move
import com.checkmatey.core.chess.PieceColor
import com.checkmatey.core.chess.PieceType
import com.checkmatey.core.chess.Position
import kotlin.random.Random

/**
 * The pure-Kotlin engine, tuned for speed and strength while staying dependency-free:
 *
 * - **Negamax + alpha-beta** with **quiescence search** at the leaves (resolves captures so
 *   material is judged after the dust settles — no horizon-effect blunders).
 * - **Pseudo-legal search**: moves are generated by movement rules only and validated when
 *   applied (own king safe?). This halves the per-node work versus filtering legal moves
 *   up front, because filtering itself had to apply every move.
 * - **Move ordering**: transposition-table move first, then captures by MVV-LVA (most valuable
 *   victim, least valuable attacker), then killer moves — better ordering means alpha-beta
 *   prunes far more of the tree.
 * - **Transposition table** keyed by Zobrist hash: positions reached via different move orders
 *   are searched once, with stored bounds and best moves reused.
 * - **Iterative deepening** at the root: each depth's result orders the next, and if the node
 *   budget runs out the last completed depth's best move stands.
 *
 * A single instance runs one search at a time (callers hop to a background dispatcher).
 */
class KotlinMinimaxEngine : Engine {

    private var nodes = 0
    private val tt = HashMap<Long, TtEntry>()
    private val killers = Array(MAX_PLY) { arrayOfNulls<Move>(2) }

    override fun evaluate(position: Position): Int = Evaluation.evaluate(position)

    override fun chooseMove(position: Position, level: BotLevel, random: Random): Move? {
        val moves = position.legalMoves()
        if (moves.isEmpty()) return null
        if (random.nextDouble() < level.blunderChance) {
            return moves[random.nextInt(moves.size)]
        }
        return bestMove(position, level.searchDepth)
    }

    override fun evaluateMove(before: Position, move: Move, depth: Int): Int {
        startSearch()
        return -negamax(before.applyMove(move), depth - 1, NEG_INF, -NEG_INF, ply = 1)
    }

    override fun bestMove(position: Position, depth: Int): Move? {
        startSearch()
        val rootMoves = position.legalMoves()
        if (rootMoves.isEmpty()) return null
        if (rootMoves.size == 1) return rootMoves.first()

        var best = rootMoves.first()
        var ordered = rootMoves
        for (d in 1..depth) {
            if (nodes > NODE_BUDGET) break // keep the last completed depth's answer
            var alpha = NEG_INF
            var iterBest = ordered.first()
            val scored = ArrayList<Pair<Move, Int>>(ordered.size)
            for (move in ordered) {
                val score = -negamax(position.applyMove(move), d - 1, NEG_INF, -alpha, ply = 1)
                scored.add(move to score)
                if (score > alpha) {
                    alpha = score
                    iterBest = move
                }
            }
            best = iterBest
            // Next iteration searches the best candidates first — cheap, big pruning win.
            ordered = scored.sortedByDescending { it.second }.map { it.first }
        }
        return best
    }

    // ---- Core search --------------------------------------------------------------------

    private fun negamax(position: Position, depth: Int, alphaIn: Int, beta: Int, ply: Int): Int {
        nodes++
        if (depth <= 0) return quiescence(position, alphaIn, beta, QUIESCENCE_PLIES)
        if (nodes > NODE_BUDGET) return evaluateForSideToMove(position)

        var alpha = alphaIn
        val key = ZobristKeys.hash(position)
        val entry = tt[key]
        if (entry != null && entry.depth >= depth && !isMateScore(entry.score)) {
            when (entry.flag) {
                TtFlag.EXACT -> return entry.score
                TtFlag.LOWER -> if (entry.score >= beta) return entry.score
                TtFlag.UPPER -> if (entry.score <= alpha) return entry.score
            }
        }

        val moves = ordered(position, position.pseudoLegalMoves(), entry?.move, ply)
        val mover = position.sideToMove
        var legalFound = false
        var best = NEG_INF
        var bestMove: Move? = null
        for (move in moves) {
            val child = position.applyMove(move)
            if (child.isKingAttacked(mover)) continue // pseudo-legal move left our king hanging
            legalFound = true
            val score = -negamax(child, depth - 1, -beta, -alpha, ply + 1)
            if (score > best) {
                best = score
                bestMove = move
            }
            if (best > alpha) alpha = best
            if (alpha >= beta) {
                rememberKiller(position, move, ply)
                break
            }
        }
        if (!legalFound) {
            return if (position.isInCheck()) -(MATE - ply) else 0 // mate (prefer faster) / stalemate
        }

        if (!isMateScore(best) && tt.size < TT_MAX) {
            val flag = when {
                best <= alphaIn -> TtFlag.UPPER
                best >= beta -> TtFlag.LOWER
                else -> TtFlag.EXACT
            }
            tt[key] = TtEntry(depth, best, flag, bestMove)
        }
        return best
    }

    /** Resolve pending captures so material is judged after the dust settles. */
    private fun quiescence(position: Position, alphaIn: Int, beta: Int, qPlies: Int): Int {
        nodes++
        val standPat = evaluateForSideToMove(position)
        if (standPat >= beta) return beta
        if (qPlies <= 0 || nodes > NODE_BUDGET) return standPat

        var alpha = maxOf(alphaIn, standPat)
        val mover = position.sideToMove
        val captures = position.pseudoLegalMoves()
            .filter { position.pieceAt(it.to) != null || it.isEnPassant }
            .sortedByDescending { mvvLva(position, it) }
        for (move in captures) {
            val child = position.applyMove(move)
            if (child.isKingAttacked(mover)) continue
            val score = -quiescence(child, -beta, -alpha, qPlies - 1)
            if (score >= beta) return beta
            if (score > alpha) alpha = score
        }
        return alpha
    }

    // ---- Move ordering ------------------------------------------------------------------

    private fun ordered(position: Position, moves: List<Move>, ttMove: Move?, ply: Int): List<Move> {
        val k = killers.getOrNull(ply)
        return moves.sortedByDescending { move ->
            when {
                ttMove != null && move == ttMove -> 1_000_000
                position.pieceAt(move.to) != null || move.isEnPassant -> 10_000 + mvvLva(position, move)
                k != null && (move == k[0] || move == k[1]) -> 5_000
                else -> 0
            }
        }
    }

    /** Most valuable victim first, least valuable attacker as tiebreak. */
    private fun mvvLva(position: Position, move: Move): Int {
        val victim = position.pieceAt(move.to)?.type ?: PieceType.PAWN // en passant captures a pawn
        val attacker = position.pieceAt(move.from)?.type ?: PieceType.PAWN
        return Evaluation.value(victim) * 10 - Evaluation.value(attacker)
    }

    private fun rememberKiller(position: Position, move: Move, ply: Int) {
        if (ply >= MAX_PLY) return
        if (position.pieceAt(move.to) != null || move.isEnPassant) return // killers are quiet moves
        val slot = killers[ply]
        if (slot[0] != move) {
            slot[1] = slot[0]
            slot[0] = move
        }
    }

    // ---- Bookkeeping --------------------------------------------------------------------

    private fun startSearch() {
        nodes = 0
        if (tt.size >= TT_MAX) tt.clear()
    }

    private fun evaluateForSideToMove(position: Position): Int {
        val white = Evaluation.evaluate(position)
        return if (position.sideToMove == PieceColor.WHITE) white else -white
    }

    private fun isMateScore(score: Int): Boolean = score > MATE - 1000 || score < -(MATE - 1000)

    private enum class TtFlag { EXACT, LOWER, UPPER }
    private data class TtEntry(val depth: Int, val score: Int, val flag: TtFlag, val move: Move?)

    companion object {
        const val MATE = 1_000_000

        private const val NEG_INF = -2_000_000
        private const val QUIESCENCE_PLIES = 12
        private const val NODE_BUDGET = 400_000
        private const val MAX_PLY = 64
        private const val TT_MAX = 200_000
    }
}

/** Zobrist hashing: a stable 64-bit key per position (placement, side, castling, en passant). */
private object ZobristKeys {
    private val rng = Random(20260718)
    private val pieces = LongArray(12 * 64) { rng.nextLong() }
    private val side = rng.nextLong()
    private val castling = LongArray(16) { rng.nextLong() }
    private val epFile = LongArray(8) { rng.nextLong() }

    fun hash(p: Position): Long {
        var h = 0L
        for (i in 0..63) {
            val piece = p.squares[i] ?: continue
            val idx = (piece.type.ordinal * 2 + if (piece.color == PieceColor.WHITE) 0 else 1) * 64 + i
            h = h xor pieces[idx]
        }
        if (p.sideToMove == PieceColor.BLACK) h = h xor side
        var c = 0
        if (p.castling.whiteKing) c = c or 1
        if (p.castling.whiteQueen) c = c or 2
        if (p.castling.blackKing) c = c or 4
        if (p.castling.blackQueen) c = c or 8
        h = h xor castling[c]
        p.enPassantTarget?.let { h = h xor epFile[it.file] }
        return h
    }
}
